### ISSUE TITLE
MetricAgeOffIterator creating illegal ranges

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/timely#132]
The MetricAgeOffIterator has been seen on multiple systems to throw an IllegalArgumentException: Start key must be less than end key in range:

at org.apache.accumulo.core.data.Range.<init>(Range.java:175)
at timely.store.MetricAgeOffIterator.seekPastAgedOffMetricData(MetricAgeOffIterator.java:156)
at timely.store.MetricAgeOffIterator.seekIfNecessary(MetricAgeOffIterator.java:90)
at timely.store.MetricAgeOffIterator.seek(MetricAgeOffIterator.java:179)

**Comment by ivakegg** [comment]
It appears that the seekPastAgedOffMetricData simply needs to guard against attempting to seek past the end of the initial range.
