### ISSUE TITLE
Extreme query start and stop times produce errors

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#77]
This is vague and probably more of a reminder to look into this more but I've noticed some errors when adjusting the query timestamps while working with the web socket. My guess is it's not a web socket specific thing, but I haven't dug into it. i was using the web socket query operation and timely standalone docker-compose setup for this. Here's what I've captured so far:

setting start time of 0 to stop time of now fails, even with only a little data in the system.

```
timely_1   | 2016-09-01 14:30:13,638 WARN  [batch scanner 2990- 1 looking up 1 ranges at acd1ffcae3a4:43079] impl.TabletServerBatchReaderIterator (TabletServerBatchReaderIterator.java:run(378)) - Error on server acd1ffcae3a4:43079
timely_1   | org.apache.accumulo.core.client.impl.AccumuloServerException: Error on server acd1ffcae3a4:43079
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:695)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator$QueryTask.run(TabletServerBatchReaderIterator.java:349)
timely_1   |   	at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
timely_1   |   	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
timely_1   |   	at java.lang.Thread.run(Thread.java:745)
timely_1   | Caused by: org.apache.thrift.TApplicationException: Internal error processing continueMultiScan
timely_1   |   	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
timely_1   |   	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.recv_continueMultiScan(TabletClientService.java:344)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.continueMultiScan(TabletClientService.java:330)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:663)
timely_1   |   	... 6 more
timely_1   | 2016-09-01 14:30:13.724  WARN 17 --- [ntLoopGroup-6-2] i.n.c.DefaultChannelPipeline             : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
timely_1   |
timely_1   | java.lang.RuntimeException: org.apache.accumulo.core.client.impl.AccumuloServerException: Error on server acd1ffcae3a4:43079
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:181)
timely_1   |   	at timely.store.DataStoreImpl.query(DataStoreImpl.java:463)
timely_1   |   	at timely.netty.websocket.timeseries.WSQueryRequestHandler.channelRead0(WSQueryRequestHandler.java:29)
timely_1   |   	at timely.netty.websocket.timeseries.WSQueryRequestHandler.channelRead0(WSQueryRequestHandler.java:17)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:147)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066)
timely_1   |   	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1279)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:889)
timely_1   |   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
timely_1   |   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
timely_1   |   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
timely_1   |   	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:136)
timely_1   |   	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
timely_1   |   	at java.lang.Thread.run(Thread.java:745)
timely_1   | Caused by: org.apache.accumulo.core.client.impl.AccumuloServerException: Error on server acd1ffcae3a4:43079
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:695)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator$QueryTask.run(TabletServerBatchReaderIterator.java:349)
timely_1   |   	at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
timely_1   |   	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
timely_1   |   	... 1 more
timely_1   | Caused by: org.apache.thrift.TApplicationException: Internal error processing continueMultiScan
timely_1   |   	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
timely_1   |   	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.recv_continueMultiScan(TabletClientService.java:344)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.continueMultiScan(TabletClientService.java:330)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:663)
timely_1   |   	... 6 more
timely_1   |
```

setting stop time far in the future produces an OOM. are result buffers pre-allocated?

```
timely_1   | java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:181)
timely_1   |   	at timely.store.DataStoreImpl.query(DataStoreImpl.java:463)
timely_1   |   	at timely.netty.websocket.timeseries.WSQueryRequestHandler.channelRead0(WSQueryRequestHandler.java:29)
timely_1   |   	at timely.netty.websocket.timeseries.WSQueryRequestHandler.channelRead0(WSQueryRequestHandler.java:17)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:147)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
timely_1   |   	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066)
timely_1   |   	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
timely_1   |   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
timely_1   |   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1279)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
timely_1   |   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
timely_1   |   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:889)
timely_1   |   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
timely_1   |   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
timely_1   |   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
timely_1   |   	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:136)
timely_1   |   	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
timely_1   |   	at java.lang.Thread.run(Thread.java:745)
timely_1   | Caused by: java.lang.OutOfMemoryError: Java heap space
timely_1   |   	at org.apache.thrift.protocol.TCompactProtocol.readBinary(TCompactProtocol.java:669)
timely_1   |   	at org.apache.accumulo.core.data.thrift.TKeyValue$TKeyValueStandardScheme.read(TKeyValue.java:439)
timely_1   |   	at org.apache.accumulo.core.data.thrift.TKeyValue$TKeyValueStandardScheme.read(TKeyValue.java:416)
timely_1   |   	at org.apache.accumulo.core.data.thrift.TKeyValue.read(TKeyValue.java:355)
timely_1   |   	at org.apache.accumulo.core.data.thrift.MultiScanResult$MultiScanResultStandardScheme.read(MultiScanResult.java:861)
timely_1   |   	at org.apache.accumulo.core.data.thrift.MultiScanResult$MultiScanResultStandardScheme.read(MultiScanResult.java:840)
timely_1   |   	at org.apache.accumulo.core.data.thrift.MultiScanResult.read(MultiScanResult.java:742)
timely_1   |   	at org.apache.accumulo.core.data.thrift.InitialMultiScan$InitialMultiScanStandardScheme.read(InitialMultiScan.java:428)
timely_1   |   	at org.apache.accumulo.core.data.thrift.InitialMultiScan$InitialMultiScanStandardScheme.read(InitialMultiScan.java:405)
timely_1   |   	at org.apache.accumulo.core.data.thrift.InitialMultiScan.read(InitialMultiScan.java:346)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$startMultiScan_result$startMultiScan_resultStandardScheme.read(TabletClientService.java:10185)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$startMultiScan_result$startMultiScan_resultStandardScheme.read(TabletClientService.java:10170)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$startMultiScan_result.read(TabletClientService.java:10109)
timely_1   |   	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.recv_startMultiScan(TabletClientService.java:317)
timely_1   |   	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.startMultiScan(TabletClientService.java:297)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator.doLookup(TabletServerBatchReaderIterator.java:634)
timely_1   |   	at org.apache.accumulo.core.client.impl.TabletServerBatchReaderIterator$QueryTask.run(TabletServerBatchReaderIterator.java:349)
timely_1   |   	at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
timely_1   |   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
timely_1   |   	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
timely_1   |   	... 1 more
timely_1   |
```

**Comment by dlmarion** [comment]
Do you have the errors from the tablet servers?

**Comment by dlmarion** [comment]
Replicated your issue. On the tablet server, the DownsampleIterator creates an array with size based on the number of downsample buckets in your time range. The array can't be larger than Integer.MAX_VALUE. The solution here is to either reduce your time range or increase your downsample time period.

**Comment by dlmarion** [comment]
We should be able to catch this earlier in the query processing and return an error before the query gets submitted to Accumulo.

**Comment by klucar** [comment]
I figured something like that was up. That's just the second error or both?

**Comment by klucar** [comment]
This actually breaks the web socket idea because we should chunk results over the web socket so timely doesn't need all the results in memory at any time. I'm starting in on the subscription API though, so maybe that's better, I'll see.
